[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.26.0",
    "google-generativeai>=0.8.5",
    "googletrans>=4.0.2",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.0",
]
